version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 2
    reviewers:
      - "MacPaw/platform-frontend"
    allowed_updates:
      - match:
          update_type: "security"
